(alumni request) Update officer photos, names, and bios.
ABTech/abtech.org pull request #129
Opened 2022-08-21 22:44 UTC by clariseliu

i do not know how to render the website, so things might definitely be wrong.

2022-08-21 23:04 UTC, DaAwesomeP requested changes
Please rename `20220821_173446.jpg` accordingly. See other comments in review.

Otherwise, looks good!

2022-08-21 23:04 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +
Please remove this extra line.

2022-08-21 23:04 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +
Please remove this extra line.

2022-08-21 23:04 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +    },
Please remove this trailing comma.

2022-08-21 23:04 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +
Please remove this extra line.

2022-08-23 04:29 UTC, clariseliu commented
oof sorry will do this asap

2022-08-25 21:10 UTC, clariseliu commented
depression

2022-08-26 00:26 UTC, DaAwesomeP requested changes
Sorry, one more small thing preventing this from working (along wit the small minor things). You're missing an opening curly bracket in one spot.

2022-08-26 00:26 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +    },
Please remove the extra space at end of line.

2022-08-26 00:26 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +    },
Please remove the extra spaces at end of line.

2022-08-26 00:26 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +
Please remove the blank line.

2022-08-26 00:26 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +    {
Missing closing bracket from previous block (will error).

2022-09-07 14:22 UTC, DaAwesomeP commented
@clariseliu any updates?

2022-09-08 02:04 UTC, DaAwesomeP approved these changes

2022-09-08 02:05 UTC, merged