Add Peach Tree Rascals, IMO X Brummies X Jordy (First Tartan Turn it Up Concert)
ABTech/abtech.org pull request #149
Opened 2022-12-31 03:35 UTC by IEYU

2022-12-31 03:38 UTC, izhanchang approved these changes
looks good!

2022-12-31 07:20 UTC, DaAwesomeP requested changes
Please also submit against the dev branch, not main.

2022-12-31 07:20 UTC, DaAwesomeP commented on _data/events_events.json
> +                "venue":"Cohon Center - Rangos 123",
Please match the format used by the other Rangos events.

2023-01-01 14:11 UTC, DaAwesomeP commented
@IEYU Updated Rangos part looks good, but please change the base branch to `dev` and then this is good to go!

2023-01-01 14:12 UTC, DaAwesomeP commented
Oh I see! Closing in favor of #151

2023-01-01 14:12 UTC, closed without merging