Added events past Oct 22
ABTech/abtech.org pull request #159
Opened 2023-08-20 00:09 UTC by wjiang42

Added:
 - AB Spring Concert - COIN and Bren Joy
 - AB Speakers - Stephanie Hsu
 - AB Speakers - Jennette McCurdy
 - AB Comedy - Melissa Villasenor
 - UE - Allegheny County Executive Debate
 - AB Winter Concert - Tiffany Day

2023-08-30 19:51 UTC, DaAwesomeP requested changes
Just some minor things! Mainly missing the officer photo assets.

2023-08-30 19:51 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> -        "img": "astrasse.jpg",
Please also remove the old unused officer photos

2023-08-30 19:51 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +        "desc": "I'm Queenie! Junior in Computational Finance minoring in Drama and Behavioral Economics. I love swimming, hiking, participating in theatre (watching/ producing!). Fun fact about me -
Extra spaces after the slashes

2023-08-30 19:51 UTC, DaAwesomeP commented on _data/people_currentcrew_officers.json
> +        "img": "yiyug.jpg",
New images need to be added/uploaded to the pull

2023-08-30 20:03 UTC, wjiang42 commented on _data/people_currentcrew_officers.json
> +        "desc": "I'm Queenie! Junior in Computational Finance minoring in Drama and Behavioral Economics. I love swimming, hiking, participating in theatre (watching/ producing!). Fun fact about me -
Do you mean dashes (--)?

2023-09-01 14:45 UTC, DaAwesomeP commented
@wjiang42 Let me know when you're ready for another review by clicking the little circle-arrow icon!

2023-09-01 19:59 UTC, wjiang42 commented
Did I request a review? I clicked some buttons and do not know if they worked

2023-09-04 01:41 UTC, DaAwesomeP approved these changes

2023-09-04 01:41 UTC, merged